name: Terraform CI/CD with Manual Approval

on:
  push:
    branches: ["main"]

env:
  ENVIRONMENT: dev
  AWS_REGION: us-east-1
  ROLE_ARN_TERRAFORM: arn:aws:iam::579254390465:role/github-actions-terraform-role
  TF_WORKING_DIR: infra/envs/${{ env.ENVIRONMENT }}

permissions:
  id-token: write
  contents: read

# 🔥 Reusable steps
jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS (Plan)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN_TERRAFORM }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Plan
        run: terraform plan
        working-directory: ${{ env.TF_WORKING_DIR }}

  apply:
    name: Terraform Apply (Manual Approval)
    needs: plan
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS (Apply)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN_TERRAFORM }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ${{ env.TF_WORKING_DIR }}
