name: Terraform CI/CD with Manual Approval

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::579254390465:role/github-actions-terraform-role
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: infra/envs/dev

      - name: Terraform Validate
        run: terraform validate
        working-directory: infra/envs/dev

      - name: Terraform Plan
        run: terraform plan
        working-directory: infra/envs/dev

  apply:
    name: Terraform Apply (Manual Approval)
    needs: plan
    runs-on: ubuntu-latest

    # 🔥 ESSA LINHA ativa o approval manual
    environment:
      name: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::123456789012:role/github-actions-terraform-role
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: infra/envs/dev

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: infra/envs/dev
