name: Terraform Backend Bootstrap

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ROLE_ARN: arn:aws:iam::579254390465:role/github-actions-terraform-role

concurrency:
  group: terraform-bootstrap
  cancel-in-progress: false

jobs:
  bootstrap:
    name: Create Terraform Backend (S3 + DynamoDB)
    runs-on: ubuntu-latest

    environment:
      name: bootstrap

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # OIDC AWS AUTH
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      # Terraform Setup
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Init
      - name: Terraform Init
        run: terraform init

      # Validate
      - name: Terraform Validate
        run: terraform validate

      # Plan
      - name: Terraform Plan
        run: terraform plan

      # Apply (criação real)
      - name: Terraform Apply
        run: terraform apply -auto-approve